# Yang wajib diisi
# 1. nama worker (ubah juga di Cargo.toml)
# 2. account id cloudflare
# 3. KV Storage
# 4. id KV Storage tadi
# 5. UUID

# ===============[ nama worker ]=================
name = "vpn"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true

# ===============[ account id ]==================
account_id = "2683d7bf863addd5c9cde03ac8d0254a"
workers_dev = true

# ===============[ KV STORAGE ]==================
[[kv_namespaces]]
binding = "AIO"
id = "0a64144e5eb940a0aff3aeb8aae698f0"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

# =================[ UUID V4 ]===================
[vars]
UUID = "bbe13818-3d82-4127-aa2a-cbc209a6b7e4"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/vapaxemu/pp.ua/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/vapaxemu/pp.ua/refs/heads/main/web/sub.html"

# ------- Dimodifikasi oleh: @vpnjatimbot -------
